lint:
  actions_awsfulltest: false
  files_exist:
    - .github/ISSUE_TEMPLATE/config.yml
    - CODE_OF_CONDUCT.md
    - assets/nf-core-downloadvepcache_logo_light.png
    - conf/modules.config
    - conf/test_full.config
    - docs/images/nf-core-downloadvepcache_logo_dark.png
    - docs/images/nf-core-downloadvepcache_logo_light.png
  modules_config: false
  multiqc_config: false
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - params.input
nf_core_version: 3.3.2
repository_type: pipeline
template:
  author: Maxime U Garcia
  description: Download VEP cache for annotation-cache
  force: false
  is_nfcore: false
  name: downloadvepcache
  org: annotation-cache
  outdir: .
  skip_features:
    - fastqc
    - igenomes
    - multiqc
    - seqera_platform
  version: "114.2"
