lint:
  actions_ci: false
  files_exist:
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awsfulltest.yml
    - .github/workflows/awstest.yml
    - CODE_OF_CONDUCT.md
    - assets/multiqc_config.yml
    - assets/nf-core-downloadvepcache_logo_light.png
    - conf/igenomes.config
    - conf/modules.config
    - conf/test_full.config
    - docs/images/nf-core-downloadvepcache_logo_dark.png
    - docs/images/nf-core-downloadvepcache_logo_light.png
    - lib/WorkflowDownloadvepcache.groovy
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-downloadvepcache_logo_light.png
    - docs/images/nf-core-downloadvepcache_logo_light.png
    - docs/images/nf-core-downloadvepcache_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - params.input
  schema_lint: false
repository_type: pipeline
template:
  prefix: annotation-cache
  skip: []
